# src/oscarcrab/config.yaml
# Unified configuration for Oscar Crab LLM backends

model:
  ollama: "mistral"
  transformers: "microsoft/phi-3-mini"

generation:
  max_tokens: 128
  temperature: 0.7
  top_p: 0.9
  top_k: 50

ollama:
  server_url: "http://localhost:11434"
  timeout: 30
